# Numpy

In [ ]:
# menggunakan library numpy untuk operasi array
import numpy as np # import numpy library

Array dengan rank 1 dan panjang 3.

In [2]:
[1, 2, 3]

[1, 2, 3]

Array dengan rank 2 dan panjang 3.

In [3]:
[[1, 2, 3], [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

Array menggunakan Numpy

In [ ]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


**ndarray**: nama class atau tipe data untuk sebuah numpy array.

In [ ]:
# Bakal menghasilkan error karena parameter untuk np.array
# harus berupa array
# a = np.array(1, 2, 3)

---

# Properties
* **ndarray.ndim**: dimensi (rank) dari sebuah numpy array.
* **ndarray.shape**: jumlah baris dan kolum dari sebuah numpy array.
* **ndarray.size**: jumlah elemen di dalam numpy array.
* **ndarray.dtype**: tipe data dari elemen yang ada di numpy array.
* **ndarray.itemsize**: ukuran elemen (bytes) yang ada di numpy array.
* **ndarray.data**: buffer untuk menyimpan elemen-elemen di dalam numpy array.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

In [ ]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(3,)
3
int64
8


In [ ]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

2
(2, 3)
6
int64
8


---

# Create Numpy Arrays

* **np.zeros**: isinya semua 0, berikan baris dan kolom
* **np.ones**: isinya semua 1, berikan baris dan kolom
* **np.arange**: isi scope (dari berapa ke berapa) dan bisa selisih antar angka
* **np.linspace**: isi scope dan jumlah elemen yang diinginkan
* **np.random.random**: isi angka acak, berikan baris dan kolom

In [ ]:
np.zeros((3, 3)) # membuat array 3x3 berisi nol

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3, 3)) # membuat array 3x3 berisi satu

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(1, 2, 0.2) # membuat array dengan nilai dari 1 sampai 2 dengan step 0.2

array([1. , 1.2, 1.4, 1.6, 1.8])

In [ ]:
np.linspace(1, 3, 10) # membuat array dengan 10 nilai yang terdistribusi merata antara 1 dan 3

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [ ]:
np.random.random((2, 3)) # membuat array 2x3 dengan nilai random antara 0 dan 1

array([[0.63014662, 0.95003617, 0.30874054],
       [0.58230916, 0.25008352, 0.86187682]])

# Shape and Operation

* **reshape**: mengubah dimensi/shape dari sebuah numpy array.
* **vstack**: stack (menggabungkan) numpy arrays secara vertikal.
* **hstack**: stack numpy arrays secara horizontal.
* **vsplit**: split (membagi) numpy arrays secara vertikal.
* **hsplit**: split numpy arrays secara horizontal.

In [22]:
a = np.array([(1, 2, 3), (4, 5, 6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = a.reshape(3, -1) # mengubah ke 3 baris dan kolomnya otomatis disesuaikan
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
b = np.array([(7, 8), (9, 10)])
b

array([[ 7,  8],
       [ 9, 10]])

In [ ]:
np.vstack((a, b)) # menggabungkan array a dan b secara vertikal

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [47]:
c = np.array([(11, 12, 13), (14, 15, 16)])
c

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
a = a.reshape(2, -1) # mengubah ke 2 baris dan kolomnya otomatis disesuaikan
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d = np.hstack((a, c)) # menggabungkan array a dan c secara horizontal
d

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [49]:
d

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [ ]:
np.vsplit(d, 2) # membagi array d menjadi 2 bagian secara vertikal

[array([[ 1,  2,  3, 11, 12, 13]]), array([[ 4,  5,  6, 14, 15, 16]])]

In [ ]:
np.hsplit(d, 3) # membagi array d menjadi 3 bagian secara horizontal

[array([[1, 2],
        [4, 5]]),
 array([[ 3, 11],
        [ 6, 14]]),
 array([[12, 13],
        [15, 16]])]

In [ ]:
np.hsplit(d, (1, 3)) # split/bagi setelah kolom 1 dan kolom 3

[array([[1],
        [4]]),
 array([[2, 3],
        [5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]])]

# Indexing

In [ ]:
data = np.arange(100, 200) # membuat array dengan nilai 100-199
data

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [ ]:
data[0]

100

In [ ]:
fives = np.arange(0, 100, 5) # membuat array dengan kelipatan 5 dari 0-95
fives

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
data[fives] # ambil elemen di index sesuai nilai pada array fives

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [ ]:
data2D = data.reshape(10, -1) # mengubah data menjadi array 2D dengan 10 baris
data2D

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [ ]:
data2D[2] # ambil baris ke-2

array([120, 121, 122, 123, 124, 125, 126, 127, 128, 129])

In [ ]:
data2D[2, 1] # ambil elemen di baris ke-2 dan kolom ke-1

121

In [ ]:
data2D[-2, -1] # ambil elemen di baris ke-2 dari akhir dan kolom terakhir

189

In [ ]:
data2D[:, 3] # ambil semua baris di kolom ke-3

array([103, 113, 123, 133, 143, 153, 163, 173, 183, 193])

In [ ]:
# baris 1, 2 dan 3 
# kolom 3 dan 4
data2D[1:4, 3:5] # ambil sub-array dari baris 1-3 dan kolom 3-4

array([[113, 114],
       [123, 124],
       [133, 134]])

# Mathematics

In [ ]:
# operasi matematika dasar pada array numpy
numbers = np.random.random((5, 5)) # membuat array 5x5 dengan nilai random antara 0 dan 1
numbers

array([[0.99796906, 0.88465506, 0.31232937, 0.64744161, 0.32130801],
       [0.29320681, 0.49971834, 0.83641279, 0.47581321, 0.47893152],
       [0.90906596, 0.86614588, 0.67717712, 0.12386656, 0.78903481],
       [0.43284819, 0.90989302, 0.77062018, 0.04862614, 0.52520144],
       [0.55981027, 0.89984193, 0.50626032, 0.94875579, 0.04810393]])

In [54]:
print(np.amin(numbers)) # nilai minimum dari array
print(np.amax(numbers)) # nilai maksimum dari array
print(np.average(numbers)) # nilai rata-rata dari array
print(np.mean(numbers)) # nilai mean dari array
print(np.median(numbers)) # nilai median dari array
print(np.sum(numbers)) # jumlah semua elemen dalam array

0.04810392864476598
0.9979690645886877
0.5905214930065944
0.5905214930065944
0.5598102659157278
14.763037325164861


In [ ]:
np.sqrt(numbers) # menghitung akar kuadrat dari setiap elemen dalam array

array([[0.61547974, 0.85228002, 0.54680397, 0.22307626, 0.43140801],
       [0.47926834, 0.73732652, 0.97268266, 0.52852609, 0.52517545],
       [0.96532388, 0.40034836, 0.865496  , 0.64956627, 0.82594118],
       [0.90413679, 0.73674004, 0.31745471, 0.87974811, 0.82572021],
       [0.41486882, 0.2993236 , 0.86914608, 0.91128326, 0.76815329]])

In [ ]:
np.sin(numbers) # menghitung nilai sinus dari setiap elemen dalam array

array([[0.36982003, 0.66416866, 0.29455955, 0.04974248, 0.1850403 ],
       [0.22768361, 0.51726354, 0.81114752, 0.27572112, 0.2723257 ],
       [0.80272468, 0.15959345, 0.68096776, 0.40952773, 0.63048573],
       [0.72941291, 0.51652347, 0.100607  , 0.69897036, 0.6302024 ],
       [0.1712676 , 0.0894748 , 0.68559078, 0.73822634, 0.55641045]])

In [ ]:
np.cos(numbers) # menghitung nilai cosinus dari setiap elemen dalam array

array([[0.92910341, 0.74758276, 0.95563313, 0.99876208, 0.98273093],
       [0.97373517, 0.85582617, 0.5848416 , 0.96123767, 0.96220513],
       [0.59634981, 0.98718282, 0.7323134 , 0.91229767, 0.77620084],
       [0.68407369, 0.85627303, 0.99492624, 0.71515064, 0.7764309 ],
       [0.98522455, 0.99598909, 0.72798714, 0.67455309, 0.83090758]])

In [55]:
np.tan(numbers) # menghitung nilai tangen dari setiap elemen dalam array

array([[1.55047264, 1.22119588, 0.32289781, 0.75617531, 0.33284169],
       [0.30190852, 0.54593682, 1.10761242, 0.51530083, 0.51925353],
       [1.28389271, 1.17609784, 0.80400315, 0.12450396, 1.00729988],
       [0.4620728 , 1.28608542, 0.97087236, 0.04866451, 0.57948914],
       [0.62668525, 1.25974923, 0.55445918, 1.39471174, 0.04814107]])

In [ ]:
sample = np.arange(1, 21) # membuat array dengan nilai 1-20
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
sample2 = np.arange(51, 71) # membuat array dengan nilai 51-70
sample2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70])

In [ ]:
sample + sample2 # penjumlahan elemen array sesuai index

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90])

In [ ]:
sample2 - sample # pengurangan elemen array sesuai index

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50])

In [ ]:
sample * sample2 # perkalian elemen array sesuai index

array([  51,  104,  159,  216,  275,  336,  399,  464,  531,  600,  671,
        744,  819,  896,  975, 1056, 1139, 1224, 1311, 1400])

In [ ]:
sample / sample2 # pembagian elemen array sesuai index

array([0.01960784, 0.03846154, 0.05660377, 0.07407407, 0.09090909,
       0.10714286, 0.12280702, 0.13793103, 0.15254237, 0.16666667,
       0.18032787, 0.19354839, 0.20634921, 0.21875   , 0.23076923,
       0.24242424, 0.25373134, 0.26470588, 0.27536232, 0.28571429])

# Matrix

In [58]:
# operasi matriks dengan numpy
matrix = np.random.randint(1, 50, 20) # membuat array dengan 20 bilangan bulat random antara 1-50 (random integer)
matrix = matrix.reshape(4, -1) # mengubah array menjadi 4x5 berbentuk 2 Dimensi
matrix

array([[11, 40, 15, 19, 39],
       [10,  7, 29, 19, 21],
       [20,  7, 21,  7, 45],
       [16, 32, 41, 33, 28]])

In [ ]:
matrix.transpose() # mentranspose/memutar matriks (baris jadi kolom dan kolom jadi baris)

array([[17, 36, 49, 27],
       [47, 27, 20, 48],
       [21, 44, 39, 27],
       [ 3, 48, 24,  7],
       [47, 48, 43, 18]])

In [63]:
np.dot(matrix, -1) # mengalikan matriks dengan skalar -1 (setiap elemen dikalikan -1)

array([[-11, -40, -15, -19, -39],
       [-10,  -7, -29, -19, -21],
       [-20,  -7, -21,  -7, -45],
       [-16, -32, -41, -33, -28]])